apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hcene/backend-image  
          imagePullPolicy: Always
          ports:
            - containerPort: 5400
          env:
            - name: PORT
              value: "5400"
            - name: REDIS_URL
              value: redis://redis-maitre:6379
            - name: REDIS_REPLICAS_URL
              value: redis://redis-esclave:6379
          resources: 
            requests: 
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m" 