apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cfg
  labels:
    name: prometheus-cfg
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets: ['backend:5400'] 