apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-esclave
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args: ["--replicaof", "redis-maitre", "6379"]
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"